# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: 归档
    url: docs/
    weight: 20
  - name: 更新
    url: blog/
    weight: 30
  - name: 我的约稿
    url: showcase/
    weight: 40
  - name: 如何构建存档库
    url: community/
    weight: 50

sidebar:
  - identifier: more
    name: 其他存档库地址
    params:
      type: separator
    weight: 1
  - identifier: Obsidian Vault
    name: "Obsidian Vault↗"
    url: "http://a.lynn77251.cn"
    weight: 2
  - identifier: hugoDocs
    name: "LOFTER↗"
    url: "https://cuirhua.lofter.com/"
    weight: 3
